# Generated by Django 5.0.4 on 2024-05-05 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daystar_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitter',
            name='date_admitted',
        ),
        migrations.RemoveField(
            model_name='sitter',
            name='duty',
        ),
    ]
