# Generated by Django 5.0.4 on 2024-05-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('daystar_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sitter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=25)),
                ('next_kin', models.CharField(max_length=100)),
                ('nin', models.IntegerField()),
                ('recomm_name', models.CharField(max_length=100)),
                ('religion', models.CharField(max_length=50)),
                ('level_education', models.CharField(max_length=200)),
                ('contact', models.IntegerField()),
            ],
        ),
    ]
