# Generated by Django 5.0.4 on 2024-05-07 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Babyreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=25)),
                ('age', models.IntegerField()),
                ('location', models.CharField(max_length=200)),
                ('name_dropper', models.CharField(max_length=100)),
                ('time_arrival', models.DateTimeField(auto_now_add=True)),
                ('name_parents', models.CharField(max_length=100)),
                ('amount_paid', models.FloatField()),
                ('period_stay', models.CharField(max_length=50)),
                ('baby_number', models.IntegerField()),
            ],
        ),
    ]
