# Generated by Django 5.0.4 on 2024-05-07 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baby_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Babyreg',
            new_name='Baby',
        ),
    ]
