# Generated by Django 5.0.4 on 2024-05-14 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baby_app', '0002_initial'),
    ]

    operations = [
    ]
