# Generated by Django 5.0.4 on 2024-05-07 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby_app', '0002_rename_babyreg_baby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baby',
            name='time_arrival',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
