# Generated by Django 5.0.4 on 2024-05-14 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baby_app', '0003_auto_20240514_1206'),
    ]

    operations = [
    ]
