# Generated by Django 5.0.4 on 2024-05-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby_app', '0003_alter_baby_time_arrival'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pickup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_picked', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(max_length=300)),
            ],
        ),
    ]
