# Generated by Django 5.0.4 on 2024-05-16 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby_app', '0003_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baby_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baby_transactions', to='baby_app.baby')),
                ('fee_paid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_transactions', to='baby_app.baby')),
            ],
        ),
    ]
