# Generated by Django 5.0.4 on 2024-05-14 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baby_app', '0004_auto_20240514_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baby',
            name='baby_number',
        ),
    ]
