# Generated by Django 5.0.4 on 2024-05-11 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby_app', '0004_pickup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baby',
            name='time_arrival',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
