# Generated by Django 5.0.4 on 2024-05-16 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby_app', '0004_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='DollPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('baby_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baby_app.baby')),
                ('doll_bought', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baby_app.item')),
            ],
        ),
    ]
