# Generated by Django 5.0.4 on 2024-05-16 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby_app', '0005_dollpay'),
        ('daystar_app', '0003_alter_sitter_nin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty_date', models.DateField(auto_now_add=True)),
                ('name_baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baby_app.baby')),
                ('name_sitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daystar_app.sitter')),
            ],
        ),
    ]
