# Generated by Django 5.0.4 on 2024-05-16 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby_app', '0006_duty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baby',
            name='amount_paid',
            field=models.IntegerField(),
        ),
    ]
