# Generated by Django 5.0.4 on 2024-05-16 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baby_app', '0008_alter_baby_time_arrival'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pickup',
            old_name='baby_info',
            new_name='baby_name',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
